spring:
  profiles:
    active: dev  # 激活开发环境配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PLMS?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ljj21041102
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.tree.plms.controller
  # 添加OpenAPI基本信息



mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml  # 已修正
  type-aliases-package: com.tree.plms.model.entity  # 修正包路径
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080